export const INDIAN_COLLEGES = [
  "Acharya Nagarjuna University, Guntur",
  "Acharya Narendra Dev College, New Delhi",
  "Alagappa University, Karaikudi",
  "Aliah University, Kolkata",
  "Aligarh Muslim University, Aligarh",
  "All India Institute of Medical Sciences, New Delhi",
  "Alliance University, Bengaluru",
  "Amity University, Noida",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "Andhra University, Visakhapatnam",
  "Anna University, Chennai",
  "Annamalai University, Chidambaram",
  "Assam Don Bosco University, Guwahati",
  "Assam Engineering College, Guwahati",
  "Assam University, Silchar",
  "Atal Bihari Vajpayee Indian Institute of Information Technology and Management, Gwalior",
  "Avinashilingam Institute for Home Science and Higher Education for Women, Coimbatore",
  "B. M. S. College of Engineering, Bengaluru",
  "B. S. Abdur Rahman Crescent Institute of Science and Technology, Chennai",
  "Banasthali Vidyapith, Banasthali",
  "Bangalore Institute of Technology, Bengaluru",
  "Bangalore University, Bengaluru",
  "Bharath Institute of Higher Education and Research, Chennai",
  "Bharathiar University, Coimbatore",
  "Bharathidasan University, Tiruchirappalli",
  "Birla Institute of Technology and Science, Pilani",
  "Birla Institute of Technology, Mesra",
  "Bishop Heber College, Tiruchirappalli",
  "Bundelkhand University, Jhansi",
  "Calcutta University, Kolkata",
  "Central University of Haryana, Mahendergarh",
  "Central University of Hyderabad, Hyderabad",
  "Central University of Jammu, Jammu",
  "Central University of Karnataka, Kalaburagi",
  "Central University of Kerala, Kasaragod",
  "Central University of Rajasthan, Ajmer",
  "Chandigarh University, Mohali",
  "Chennai Institute of Technology, Chennai",
  "Christ University, Bengaluru",
  "CMR Institute of Technology, Bengaluru",
  "Cochin University of Science and Technology, Kochi",
  "College of Engineering, Guindy",
  "College of Engineering, Pune",
  "D. Y. Patil College of Engineering, Pune",
  "Dayananda Sagar College of Engineering, Bengaluru",
  "Delhi Technological University, Delhi",
  "Dibrugarh University, Dibrugarh",
  "Dr. A. P. J. Abdul Kalam Technical University, Lucknow",
  "Dr. B. R. Ambedkar National Institute of Technology, Jalandhar",
  "Dr. M. G. R. Educational and Research Institute, Chennai",
  "Fergusson College, Pune",
  "Galgotias University, Greater Noida",
  "Gandhi Institute of Technology and Management, Visakhapatnam",
  "Gauhati University, Guwahati",
  "Goa University, Taleigao",
  "Government College of Engineering, Salem",
  "Government College of Technology, Coimbatore",
  "Graphic Era Deemed to be University, Dehradun",
  "Gujarat Technological University, Ahmedabad",
  "Guru Gobind Singh Indraprastha University, Delhi",
  "Guru Nanak Dev University, Amritsar",
  "Harcourt Butler Technical University, Kanpur",
  "Hindustan Institute of Technology and Science, Chennai",
  "Indian Institute of Engineering Science and Technology, Shibpur",
  "Indian Institute of Information Technology Design and Manufacturing, Kancheepuram",
  "Indian Institute of Information Technology, Allahabad",
  "Indian Institute of Information Technology, Bangalore",
  "Indian Institute of Information Technology, Bhopal",
  "Indian Institute of Information Technology, Dharwad",
  "Indian Institute of Information Technology, Guwahati",
  "Indian Institute of Information Technology, Hyderabad",
  "Indian Institute of Information Technology, Kalyani",
  "Indian Institute of Information Technology, Kota",
  "Indian Institute of Information Technology, Lucknow",
  "Indian Institute of Information Technology, Nagpur",
  "Indian Institute of Information Technology, Pune",
  "Indian Institute of Information Technology, Sri City",
  "Indian Institute of Information Technology, Tiruchirappalli",
  "Indian Institute of Management, Ahmedabad",
  "Indian Institute of Management, Bangalore",
  "Indian Institute of Management, Calcutta",
  "Indian Institute of Management, Indore",
  "Indian Institute of Management, Kozhikode",
  "Indian Institute of Management, Lucknow",
  "Indian Institute of Science Education and Research, Bhopal",
  "Indian Institute of Science Education and Research, Kolkata",
  "Indian Institute of Science Education and Research, Mohali",
  "Indian Institute of Science Education and Research, Pune",
  "Indian Institute of Science Education and Research, Thiruvananthapuram",
  "Indian Institute of Science, Bengaluru",
  "Indian Institute of Space Science and Technology, Thiruvananthapuram",
  "Indian Institute of Technology, Bhilai",
  "Indian Institute of Technology, Bhubaneswar",
  "Indian Institute of Technology, Bombay",
  "Indian Institute of Technology, Delhi",
  "Indian Institute of Technology, Dharwad",
  "Indian Institute of Technology, Gandhinagar",
  "Indian Institute of Technology, Goa",
  "Indian Institute of Technology, Guwahati",
  "Indian Institute of Technology, Hyderabad",
  "Indian Institute of Technology, Indore",
  "Indian Institute of Technology, Jammu",
  "Indian Institute of Technology, Jodhpur",
  "Indian Institute of Technology, Kanpur",
  "Indian Institute of Technology, Kharagpur",
  "Indian Institute of Technology, Madras",
  "Indian Institute of Technology, Mandi",
  "Indian Institute of Technology, Palakkad",
  "Indian Institute of Technology, Patna",
  "Indian Institute of Technology, Roorkee",
  "Indian Institute of Technology, Ropar",
  "Indian Institute of Technology, Tirupati",
  "Indian School of Business, Hyderabad",
  "Indian Statistical Institute, Kolkata",
  "Indira Gandhi Delhi Technical University for Women, Delhi",
  "Institute of Chemical Technology, Mumbai",
  "Institute of Engineering and Management, Kolkata",
  "Institute of Engineering and Technology, Lucknow",
  "Institute of Technology, Nirma University, Ahmedabad",
  "International Institute of Information Technology, Bhubaneswar",
  "International Institute of Information Technology, Hyderabad",
  "Jadavpur University, Kolkata",
  "Jain University, Bengaluru",
  "Jamia Hamdard, New Delhi",
  "Jamia Millia Islamia, New Delhi",
  "Jawaharlal Nehru Technological University, Hyderabad",
  "Jawaharlal Nehru University, New Delhi",
  "Jaypee Institute of Information Technology, Noida",
  "JSS Academy of Technical Education, Noida",
  "JSS Science and Technology University, Mysuru",
  "K. J. Somaiya College of Engineering, Mumbai",
  "Kalasalingam Academy of Research and Education, Krishnankoil",
  "Kalinga Institute of Industrial Technology, Bhubaneswar",
  "Karunya Institute of Technology and Sciences, Coimbatore",
  "KLE Technological University, Hubballi",
  "Koneru Lakshmaiah Education Foundation, Vijayawada",
  "Kumaraguru College of Technology, Coimbatore",
  "Lady Shri Ram College for Women, New Delhi",
  "Lovely Professional University, Phagwara",
  "Loyola College, Chennai",
  "M. S. Ramaiah Institute of Technology, Bengaluru",
  "Madras Christian College, Chennai",
  "Madurai Kamaraj University, Madurai",
  "Maharaja Sayajirao University of Baroda, Vadodara",
  "Mahatma Gandhi University, Kottayam",
  "Malaviya National Institute of Technology, Jaipur",
  "Manipal Academy of Higher Education, Manipal",
  "Maulana Azad National Institute of Technology, Bhopal",
  "MIT World Peace University, Pune",
  "Motilal Nehru National Institute of Technology, Allahabad",
  "Mumbai University, Mumbai",
  "N. M. A. M. Institute of Technology, Nitte",
  "National Institute of Engineering, Mysuru",
  "National Institute of Fashion Technology, Bengaluru",
  "National Institute of Fashion Technology, Delhi",
  "National Institute of Technology, Agartala",
  "National Institute of Technology, Arunachal Pradesh",
  "National Institute of Technology, Calicut",
  "National Institute of Technology, Delhi",
  "National Institute of Technology, Durgapur",
  "National Institute of Technology, Goa",
  "National Institute of Technology, Hamirpur",
  "National Institute of Technology, Jamshedpur",
  "National Institute of Technology, Karnataka, Surathkal",
  "National Institute of Technology, Kurukshetra",
  "National Institute of Technology, Manipur",
  "National Institute of Technology, Meghalaya",
  "National Institute of Technology, Mizoram",
  "National Institute of Technology, Nagaland",
  "National Institute of Technology, Patna",
  "National Institute of Technology, Puducherry",
  "National Institute of Technology, Raipur",
  "National Institute of Technology, Rourkela",
  "National Institute of Technology, Sikkim",
  "National Institute of Technology, Silchar",
  "National Institute of Technology, Srinagar",
  "National Institute of Technology, Tiruchirappalli",
  "National Institute of Technology, Uttarakhand",
  "National Institute of Technology, Warangal",
  "National Law School of India University, Bengaluru",
  "Netaji Subhas University of Technology, Delhi",
  "Nirma University, Ahmedabad",
  "Noida Institute of Engineering and Technology, Greater Noida",
  "Osmania University, Hyderabad",
  "Panjab University, Chandigarh",
  "PES University, Bengaluru",
  "Pondicherry University, Puducherry",
  "PSG College of Technology, Coimbatore",
  "Punjab Engineering College, Chandigarh",
  "R. V. College of Engineering, Bengaluru",
  "Rajiv Gandhi Institute of Petroleum Technology, Amethi",
  "Ramakrishna Mission Vivekananda College, Chennai",
  "Rashtrasant Tukadoji Maharaj Nagpur University, Nagpur",
  "Reva University, Bengaluru",
  "S. R. M. Institute of Science and Technology, Chennai",
  "SASTRA Deemed University, Thanjavur",
  "Sathyabama Institute of Science and Technology, Chennai",
  "Savitribai Phule Pune University, Pune",
  "Shanmugha Arts, Science, Technology and Research Academy, Thanjavur",
  "Shiv Nadar University, Greater Noida",
  "Siddaganga Institute of Technology, Tumakuru",
  "Siksha O Anusandhan, Bhubaneswar",
  "Sri Krishna College of Engineering and Technology, Coimbatore",
  "Sri Ramachandra Institute of Higher Education and Research, Chennai",
  "Sri Sairam Engineering College, Chennai",
  "Sri Sivasubramaniya Nadar College of Engineering, Chennai",
  "St. Joseph's College, Tiruchirappalli",
  "St. Stephen's College, New Delhi",
  "Symbiosis Institute of Technology, Pune",
  "Tata Institute of Fundamental Research, Mumbai",
  "Tata Institute of Social Sciences, Mumbai",
  "Tezpur University, Tezpur",
  "Thapar Institute of Engineering and Technology, Patiala",
  "Thiagarajar College of Engineering, Madurai",
  "University College of Engineering, Osmania University, Hyderabad",
  "University of Allahabad, Prayagraj",
  "University of Calicut, Malappuram",
  "University of Delhi, New Delhi",
  "University of Hyderabad, Hyderabad",
  "University of Kerala, Thiruvananthapuram",
  "University of Lucknow, Lucknow",
  "University of Madras, Chennai",
  "University of Mumbai, Mumbai",
  "University of Mysore, Mysuru",
  "University of Rajasthan, Jaipur",
  "University of Science and Technology, Meghalaya",
  "University of Calcutta, Kolkata",
  "Vardhaman College of Engineering, Hyderabad",
  "Veermata Jijabai Technological Institute, Mumbai",
  "Vellore Institute of Technology, Vellore",
  "Visvesvaraya National Institute of Technology, Nagpur",
  "Visvesvaraya Technological University, Belagavi",
  "West Bengal University of Technology, Kolkata",
  "Xavier Institute of Engineering, Mumbai",
  "Yenepoya University, Mangaluru",
] as const;
